# Generated by Django 3.0.6 on 2020-08-08 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corelib', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CoreLib',
            new_name='VideoLib',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='corelib',
            new_name='videolib',
        ),
    ]
